=== dven84/yii2-gisgkh/versions/10.0.2.10/schema/address-validation/hcs-address-validation-types.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 rel. 2 (http://www.altova.com) by TeaM DJiNN (TeaM DJiNN) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://dom.gosuslugi.ru/schema/integration/address-validation/" xmlns:base="http://dom.gosuslugi.ru/schema/integration/base/" targetNamespace="http://dom.gosuslugi.ru/schema/integration/address-validation/" elementFormDefault="qualified" attributeFormDefault="unqualified" version="10.0.2.3">
	<xs:import namespace="http://dom.gosuslugi.ru/schema/integration/base/" schemaLocation="../lib/hcs-base.xsd"/>
	<xs:element name="exportAddressAdditionRequest">
		<xs:annotation>
			<xs:documentation>Запрос выгрузки заявок</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="base:BaseType">
					<xs:sequence>
						<xs:element name="LastModified" type="xs:dateTime" minOccurs="0">
							<xs:annotation>
								<xs:documentation>Забрать заявки, добавленные/обновленные после данной указанной даты</xs:documentation>
							</xs:annotation>
						</xs:element>
					</xs:sequence>
					<xs:attribute ref="base:version" use="required" fixed="10.0.1.2"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="exportAddressAdditionResponse">
		<xs:annotation>
			<xs:documentation>Ответ на запрос выгрузки заявок</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="base:BaseType">
					<xs:choice>
						<xs:element ref="tns:AggregatedRequest" minOccurs="0" maxOccurs="unbounded"/>
						<xs:element ref="base:ErrorMessage"/>
					</xs:choice>
					<xs:attribute ref="base:version" use="required" fixed="10.0.1.2"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="importVerificationResultRequest">
		<xs:annotation>
			<xs:documentation>Запрос на импорт результатов рассмотрения заявок</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="base:BaseType">
					<xs:sequence>
						<xs:element name="VerificationResult" maxOccurs="unbounded">
							<xs:annotation>
								<xs:documentation>Результат рассмотрения подзаявки</xs:documentation>
							</xs:annotation>
							<xs:complexType>
								<xs:sequence>
									<xs:element ref="base:TransportGUID"/>
									<xs:element ref="tns:SubRequestGUID"/>
									<xs:element name="Stage">
										<xs:annotation>
											<xs:documentation>Этап обработки подзаявки (перечисляемый тип, будет уточнен)</xs:documentation>
										</xs:annotation>
										<xs:complexType>
											<xs:choice>
												<xs:element name="APPROVED" type="xs:boolean" fixed="true">
													<xs:annotation>
														<xs:documentation>Утверждена</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="REJECTED">
													<xs:annotation>
														<xs:documentation>Отклонена</xs:documentation>
													</xs:annotation>
													<xs:complexType>
														<xs:sequence>
															<xs:element name="RejectReason" type="xs:string">
																<xs:annotation>
																	<xs:documentation>Причина отклонения</xs:documentation>
																</xs:annotation>
															</xs:element>
															<xs:choice minOccurs="0">
																<xs:element name="AOGUID" type="base:GUIDType">
																	<xs:annotation>
																		<xs:documentation>Дубль AOGUID</xs:documentation>
																	</xs:annotation>
																</xs:element>
																<xs:element name="HOUSEGUID" type="base:GUIDType">
																	<xs:annotation>
																		<xs:documentation>Дубль HOUSEGUID</xs:documentation>
																	</xs:annotation>
																</xs:element>
															</xs:choice>
														</xs:sequence>
													</xs:complexType>
												</xs:element>
											</xs:choice>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute ref="base:version" use="required" fixed="10.0.1.2"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="getStateResult">
		<xs:annotation>
			<xs:documentation>Возврат статуса отправленного сообщения</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="base:BaseAsyncResponseType">
					<xs:choice minOccurs="0">
						<xs:element ref="base:ErrorMessage"/>
						<xs:element name="ImportResult" type="base:CommonResultType" maxOccurs="unbounded"/>
						<xs:element ref="tns:exportAddressAdditionResponse"/>
					</xs:choice>
					<xs:attribute ref="base:version" use="required" fixed="10.0.1.2"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<!--Вспомогательные типы и элементы-->
	<xs:element name="AggregatedRequest">
		<xs:annotation>
			<xs:documentation>Заявка</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="RequestGUID" type="base:GUIDType">
					<xs:annotation>
						<xs:documentation>Идентификатор заявки</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="UpdateDate" type="xs:dateTime">
					<xs:annotation>
						<xs:documentation>Дата создания/изменения агрегирующей заявки/формирования новой версии</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="IsWithdraw" type="xs:boolean">
					<xs:annotation>
						<xs:documentation>Признак того, отозвана заявка или нет</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Location" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Месторасположение адресного объекта. Является обязательным если имеется подзаявка на дом, при это отсутствует указание улицы или доп.территории или улицы на доп. территории, в остальных случаях поле необязательно.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Description" minOccurs="0">
								<xs:annotation>
									<xs:documentation>Текстовое описание </xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="Reason" type="base:GUIDType" minOccurs="0" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Основание для добавления временного адреса. Является обязательным, если поле Описание месторасположения адресного объекта - обязательное, в остальных случаях поле необязательно.</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="HouseobjSubrequest" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Заявки на добавление дома</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="tns:SubRequestGUID"/>
							<xs:element name="Number">
								<xs:annotation>
									<xs:documentation>Номер подзаявки</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="12"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="HOUSENUM" minOccurs="0">
								<xs:annotation>
									<xs:documentation>Номер дома</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="20"/>
										<xs:minLength value="1"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="BUILDNUM" minOccurs="0">
								<xs:annotation>
									<xs:documentation>Номер корпуса</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="10"/>
										<xs:minLength value="0"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="STRUCNUM" minOccurs="0">
								<xs:annotation>
									<xs:documentation>Номер строения</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="10"/>
										<xs:minLength value="0"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="ESTSTATUS">
								<xs:annotation>
									<xs:documentation>Признак владения:
0 – не определено;
1 – владение;
2 – дом;
3 – домовладение;
4 – участок.

</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:byte">
										<xs:enumeration value="0"/>
										<xs:enumeration value="1"/>
										<xs:enumeration value="2"/>
										<xs:enumeration value="3"/>
										<xs:enumeration value="4"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="STRSTATUS" minOccurs="0">
								<xs:annotation>
									<xs:documentation>Признак строения:
0 – не определено;
1 – строение;
2 – сооружение;
3 – литер.</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:byte">
										<xs:enumeration value="0"/>
										<xs:enumeration value="1"/>
										<xs:enumeration value="2"/>
										<xs:enumeration value="3"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="HouseState" type="xs:byte">
								<xs:annotation>
									<xs:documentation>Состояние дома:
0 – не определено;
1 - Аварийный
2 - Исправный
3 - Ветхий
4 - Не выбран
									</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="OKTMO" type="base:OKTMORefType" minOccurs="0">
								<xs:annotation>
									<xs:documentation>ОКТМО</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:choice>
								<xs:element name="AOSubRequestGUID" type="base:GUIDType">
									<xs:annotation>
										<xs:documentation>Ссылка на родительскую заявку в случае создания заявок на несколько адресных объектов</xs:documentation>
									</xs:annotation>
								</xs:element>
								<xs:element name="AOGUID" type="base:GUIDType">
									<xs:annotation>
										<xs:documentation>Guid записи родительского объекта (улицы)</xs:documentation>
									</xs:annotation>
								</xs:element>
							</xs:choice>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="AddrobjSubrequest" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Заявки на добавление адресного объекта</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="tns:AOType">
								<xs:sequence>
									<xs:element ref="tns:SubRequestGUID">
										<xs:annotation>
											<xs:documentation>Идентификатор подзаявки</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="Number">
										<xs:annotation>
											<xs:documentation>Номер подзаявки</xs:documentation>
										</xs:annotation>
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:minLength value="1"/>
												<xs:maxLength value="12"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:element>
									<xs:choice minOccurs="0">
										<xs:element name="ParentSubRequestGUID" type="base:GUIDType" minOccurs="1">
											<xs:annotation>
												<xs:documentation>Guid родительской заявки на добавление адресного объекта по ФИАС</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element ref="tns:ParentGUID"/>
									</xs:choice>
								</xs:sequence>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="Addrobj" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Информация о родительских объектах, существующих в ФИАС </xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="tns:AOType">
								<xs:sequence>
									<xs:element name="AOGUID" type="base:GUIDType">
										<xs:annotation>
											<xs:documentation>Идентификатор адресного объекта</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element ref="tns:ParentGUID" minOccurs="0"/>
								</xs:sequence>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:key name="AddrobjSubrequestKey">
			<xs:selector xpath="tns:AddrobjSubrequest/tns:SubRequestGUID"/>
			<xs:field xpath="."/>
		</xs:key>
		<xs:key name="AddrobjKey">
			<xs:selector xpath="tns:Addrobj/tns:AOGUID"/>
			<xs:field xpath="."/>
		</xs:key>
		<xs:keyref name="HouseobjSubrequest_AddrobjSubrequestKeyRef" refer="tns:AddrobjSubrequestKey">
			<xs:selector xpath="tns:HouseobjSubrequest/tns:AOSubRequestGUID"/>
			<xs:field xpath="."/>
		</xs:keyref>
		<xs:keyref name="HouseobjSubrequest_AOKeyRef" refer="tns:AddrobjKey">
			<xs:selector xpath="tns:HouseobjSubrequest/tns:AOGUID"/>
			<xs:field xpath="."/>
		</xs:keyref>
		<xs:keyref name="AddrobjSubrequest_AddrobjSubrequesKeyRef" refer="tns:AddrobjSubrequestKey">
			<xs:selector xpath="tns:AddrobjSubrequest/tns:ParentSubRequestGUID"/>
			<xs:field xpath="."/>
		</xs:keyref>
		<xs:keyref name="AddrobjSubrequest_AOKeyRef" refer="tns:AddrobjKey">
			<xs:selector xpath="tns:AddrobjSubrequest/tns:ParentGUID"/>
			<xs:field xpath="."/>
		</xs:keyref>
		<xs:keyref name="Addrobj_AOKeyRef" refer="tns:AddrobjKey">
			<xs:selector xpath="tns:Addrobj/tns:ParentGUID"/>
			<xs:field xpath="."/>
		</xs:keyref>
	</xs:element>
	<xs:element name="SubRequestGUID" type="base:GUIDType">
		<xs:annotation>
			<xs:documentation>Идентификатор подзаявки</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="ParentGUID" type="base:GUIDType">
		<xs:annotation>
			<xs:documentation>Guid записи родительского объекта по ФИАС</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="AOType">
		<xs:sequence>
			<xs:element name="AOLevel">
				<xs:annotation>
					<xs:documentation>Уровень адресного объекта:
1 – уровень региона
2 – уровень автономного округа
3 – уровень района
4 – уровень города
5 – уровень внутригородской территории
6 – уровень населенного пункта
7 – уровень улицы
90 – уровень дополнительных территорий
91 – уровень подчиненных дополнительным территориям объектов
					</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:pattern value="1"/>
						<xs:pattern value="2"/>
						<xs:pattern value="3"/>
						<xs:pattern value="4"/>
						<xs:pattern value="5"/>
						<xs:pattern value="6"/>
						<xs:pattern value="7"/>
						<xs:pattern value="90"/>
						<xs:pattern value="91"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="FormalName">
				<xs:annotation>
					<xs:documentation>Формализованное наименование</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
						<xs:maxLength value="120"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ShortName">
				<xs:annotation>
					<xs:documentation>Краткое наименование</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
						<xs:maxLength value="120"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="OKTMO" type="base:OKTMORefType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>ОКТМО</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== dven84/yii2-gisgkh/versions/10.0.2.10/schema/address-validation/Примеры/1 - г. Москва, поселение Внуковское, ст. Внуково, ул. Железнодорожная, дом 2А3, корп.1, стр.4/response1.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:exportAddressAdditionResponse xmlns:tns="http://dom.gosuslugi.ru/schema/integration/address-validation/" xmlns:base="http://dom.gosuslugi.ru/schema/integration/base/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" base:version="10.0.1.2" xsi:schemaLocation="http://dom.gosuslugi.ru/schema/integration/address-validation/ ../../hcs-address-validation-types.xsd">
	<tns:AggregatedRequest>
		<tns:RequestGUID>6196c7dd-cfbb-4ca5-900f-e536c9c49282</tns:RequestGUID>
		<tns:UpdateDate>2016-08-31T09:30:47Z</tns:UpdateDate>
		<tns:IsWithdraw>false</tns:IsWithdraw>
		<tns:HouseobjSubrequest>
			<tns:SubRequestGUID>330551e0-0a6b-40bb-924f-a3ab96704304</tns:SubRequestGUID>
			<tns:Number>1</tns:Number>
			<tns:HOUSENUM>2А/3</tns:HOUSENUM>
			<tns:BUILDNUM>1</tns:BUILDNUM>
			<tns:STRUCNUM>4</tns:STRUCNUM>
			<tns:ESTSTATUS>2</tns:ESTSTATUS>
			<tns:STRSTATUS>1</tns:STRSTATUS>
			<tns:HouseState>2</tns:HouseState>
			<tns:OKTMO>
				<base:code>45941000</base:code>
				<base:name>Внутригородское муниципальное образование в городе Москве поселение Внуковское</base:name>
			</tns:OKTMO>
			<tns:AOGUID>e128507f-5307-4fd6-9171-b4183e59a9dc</tns:AOGUID>
		</tns:HouseobjSubrequest>
		<tns:Addrobj>
			<tns:AOLevel>7</tns:AOLevel>
			<tns:FormalName>Железнодорожная улица</tns:FormalName>
			<tns:ShortName>ул</tns:ShortName>
			<tns:OKTMO>
				<base:code>45941000</base:code>
				<base:name>Внутригородское муниципальное образование в городе Москве поселение Внуковское</base:name>
			</tns:OKTMO>
			<tns:AOGUID>e128507f-5307-4fd6-9171-b4183e59a9dc</tns:AOGUID>
			<tns:ParentGUID>839e2416-fdbe-4ae5-ba07-60fc7944f8fb</tns:ParentGUID>
		</tns:Addrobj>
		<tns:Addrobj>
			<tns:AOLevel>6</tns:AOLevel>
			<tns:FormalName>Станции Внуково поселок</tns:FormalName>
			<tns:ShortName>п/о</tns:ShortName>
			<tns:OKTMO>
				<base:code>45941000</base:code>
				<base:name>Внутригородское муниципальное образование в городе Москве поселение Внуковское</base:name>
			</tns:OKTMO>
			<tns:AOGUID>839e2416-fdbe-4ae5-ba07-60fc7944f8fb</tns:AOGUID>
			<tns:ParentGUID>cd7354a5-8a12-4b4d-af37-5358bde1c8e2</tns:ParentGUID>
		</tns:Addrobj>
		<tns:Addrobj>
			<tns:AOLevel>3</tns:AOLevel>
			<tns:FormalName>Внуковское поселение</tns:FormalName>
			<tns:ShortName>п</tns:ShortName>
			<tns:OKTMO>
				<base:code>45941000</base:code>
				<base:name>Внутригородское муниципальное образование в городе Москве поселение Внуковское</base:name>
			</tns:OKTMO>
			<tns:AOGUID>cd7354a5-8a12-4b4d-af37-5358bde1c8e2</tns:AOGUID>
			<tns:ParentGUID>0c5b2444-70a0-4932-980c-b4dc0d3f02b5</tns:ParentGUID>
		</tns:Addrobj>
		<tns:Addrobj>
			<tns:AOLevel>1</tns:AOLevel>
			<tns:FormalName>Москва город</tns:FormalName>
			<tns:ShortName>г</tns:ShortName>
			<tns:AOGUID>0c5b2444-70a0-4932-980c-b4dc0d3f02b5</tns:AOGUID>
		</tns:Addrobj>
	</tns:AggregatedRequest>
</tns:exportAddressAdditionResponse>

=== dven84/yii2-gisgkh/versions/10.0.2.10/schema/address-validation/Примеры/2 - Московская обл., г. Королев, мкр Болшево, ул.Береговая, дом 117, корп.А, стр.1/response2.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:exportAddressAdditionResponse xmlns:tns="http://dom.gosuslugi.ru/schema/integration/address-validation/" xmlns:base="http://dom.gosuslugi.ru/schema/integration/base/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://dom.gosuslugi.ru/schema/integration/address-validation/ ../../hcs-address-validation-types.xsd" base:version="10.0.1.2">
	<tns:AggregatedRequest>
		<tns:RequestGUID>fef23bb3-96fa-421b-993f-b9038c2f366b</tns:RequestGUID>
		<tns:UpdateDate>2016-08-31T09:30:47Z</tns:UpdateDate>
		<tns:IsWithdraw>false</tns:IsWithdraw>
		<tns:HouseobjSubrequest>
			<tns:SubRequestGUID>d7bde3dc-0b7f-4142-a6fe-cd8a6de08011</tns:SubRequestGUID>
			<tns:Number>1</tns:Number>
			<tns:HOUSENUM>11/7</tns:HOUSENUM>
			<tns:BUILDNUM>А</tns:BUILDNUM>
			<tns:STRUCNUM>1</tns:STRUCNUM>
			<tns:ESTSTATUS>2</tns:ESTSTATUS>
			<tns:STRSTATUS>1</tns:STRSTATUS>
			<tns:HouseState>2</tns:HouseState>
			<tns:OKTMO>
				<base:code>46734000</base:code>
				<base:name>Город Королев</base:name>
			</tns:OKTMO>
			<tns:AOGUID>644b1925-c8c5-4f29-9050-4f06a464c134</tns:AOGUID>
		</tns:HouseobjSubrequest>
		<tns:Addrobj>
			<tns:AOLevel>7</tns:AOLevel>
			<tns:FormalName>Береговая улица</tns:FormalName>
			<tns:ShortName>ул</tns:ShortName>
			<tns:OKTMO>
				<base:code>46734000</base:code>
				<base:name>Город Королев</base:name>
			</tns:OKTMO>
			<tns:AOGUID>644b1925-c8c5-4f29-9050-4f06a464c134</tns:AOGUID>
			<tns:ParentGUID>612d340f-edf3-4a17-a9f1-4bc52c36921d</tns:ParentGUID>
		</tns:Addrobj>
		<tns:Addrobj>
			<tns:AOLevel>6</tns:AOLevel>
			<tns:FormalName>Болшево микрорайон</tns:FormalName>
			<tns:ShortName>мкр</tns:ShortName>
			<tns:OKTMO>
				<base:code>46734000</base:code>
				<base:name>Город Королев</base:name>
			</tns:OKTMO>
			<tns:AOGUID>612d340f-edf3-4a17-a9f1-4bc52c36921d</tns:AOGUID>
			<tns:ParentGUID>819d6910-b4d1-474f-ad10-c1fa944dfca4</tns:ParentGUID>
		</tns:Addrobj>
		<tns:Addrobj>
			<tns:AOLevel>4</tns:AOLevel>
			<tns:FormalName>Королев город</tns:FormalName>
			<tns:ShortName>г</tns:ShortName>
			<tns:OKTMO>
				<base:code>46734000</base:code>
				<base:name>Город Королев</base:name>
			</tns:OKTMO>
			<tns:AOGUID>819d6910-b4d1-474f-ad10-c1fa944dfca4</tns:AOGUID>
			<tns:ParentGUID>29251dcf-00a1-4e34-98d4-5c47484a36d4</tns:ParentGUID>
		</tns:Addrobj>
		<tns:Addrobj>
			<tns:AOLevel>1</tns:AOLevel>
			<tns:FormalName>Московская область</tns:FormalName>
			<tns:ShortName>обл</tns:ShortName>
			<tns:AOGUID>29251dcf-00a1-4e34-98d4-5c47484a36d4</tns:AOGUID>
		</tns:Addrobj>
	</tns:AggregatedRequest>
</tns:exportAddressAdditionResponse>

=== dven84/yii2-gisgkh/versions/10.0.2.10/schema/address-validation/Примеры/3 - Московская обл., Волоколамский р-н, г. Волоколамск, мкр Новый, ул.Элеваторов, дом 187, корп.4, стр.А/response3.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:exportAddressAdditionResponse xmlns:tns="http://dom.gosuslugi.ru/schema/integration/address-validation/" xmlns:base="http://dom.gosuslugi.ru/schema/integration/base/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://dom.gosuslugi.ru/schema/integration/address-validation/ ../../hcs-address-validation-types.xsd" base:version="10.0.1.2">
	<tns:AggregatedRequest>
		<tns:RequestGUID>2edb7a42-ed51-4bb1-911b-57e945dbce35</tns:RequestGUID>
		<tns:UpdateDate>2016-08-31T09:30:47Z</tns:UpdateDate>
		<tns:IsWithdraw>false</tns:IsWithdraw>
		<tns:HouseobjSubrequest>
			<tns:SubRequestGUID>d850f11f-2138-4f09-8516-a58ae8ded575</tns:SubRequestGUID>
			<tns:Number>3</tns:Number>
			<tns:HOUSENUM>18/7</tns:HOUSENUM>
			<tns:BUILDNUM>4</tns:BUILDNUM>
			<tns:STRUCNUM>А</tns:STRUCNUM>
			<tns:ESTSTATUS>2</tns:ESTSTATUS>
			<tns:STRSTATUS>1</tns:STRSTATUS>
			<tns:HouseState>2</tns:HouseState>
			<tns:OKTMO>
				<base:code>46605101001</base:code>
				<base:name>город Волоколамск</base:name>
			</tns:OKTMO>
			<tns:AOGUID>ca8fb626-709c-4851-a8d6-cbfd592c3bf8</tns:AOGUID>
		</tns:HouseobjSubrequest>
		<tns:AddrobjSubrequest>
			<tns:AOLevel>7</tns:AOLevel>
			<tns:FormalName>Элеваторов улица</tns:FormalName>
			<tns:ShortName>ул</tns:ShortName>
			<tns:OKTMO>
				<base:code>46605101001</base:code>
				<base:name>город Волоколамск</base:name>
			</tns:OKTMO>
			<tns:SubRequestGUID>66e0af52-ac28-4b40-9a67-73f817283122</tns:SubRequestGUID>
			<tns:Number>2</tns:Number>
			<tns:ParentSubRequestGUID>262228bd-559d-40a1-b3a8-5f0223e840fd</tns:ParentSubRequestGUID>
		</tns:AddrobjSubrequest>
		<tns:AddrobjSubrequest>
			<tns:AOLevel>6</tns:AOLevel>
			<tns:FormalName>Новый микрорайон</tns:FormalName>
			<tns:ShortName>мкр</tns:ShortName>
			<tns:OKTMO>
				<base:code>46605101001</base:code>
				<base:name>город Волоколамск</base:name>
			</tns:OKTMO>
			<tns:SubRequestGUID>262228bd-559d-40a1-b3a8-5f0223e840fd</tns:SubRequestGUID>
			<tns:Number>1</tns:Number>
			<tns:ParentGUID>ca8fb626-709c-4851-a8d6-cbfd592c3bf8</tns:ParentGUID>
		</tns:AddrobjSubrequest>
		<tns:Addrobj>
			<tns:AOLevel>4</tns:AOLevel>
			<tns:FormalName>Волоколамск город</tns:FormalName>
			<tns:ShortName>г</tns:ShortName>
			<tns:OKTMO>
				<base:code>46605101001</base:code>
				<base:name>город Волоколамск</base:name>
			</tns:OKTMO>
			<tns:AOGUID>ca8fb626-709c-4851-a8d6-cbfd592c3bf8</tns:AOGUID>
			<tns:ParentGUID>ebceede7-cea0-48c8-b3ba-97b599feb687</tns:ParentGUID>
		</tns:Addrobj>
		<tns:Addrobj>
			<tns:AOLevel>3</tns:AOLevel>
			<tns:FormalName>Волоколамский район</tns:FormalName>
			<tns:ShortName>р-н</tns:ShortName>
			<tns:OKTMO>
				<base:code>46605000</base:code>
				<base:name>Волоколамский район</base:name>
			</tns:OKTMO>
			<tns:AOGUID>ebceede7-cea0-48c8-b3ba-97b599feb687</tns:AOGUID>
			<tns:ParentGUID>29251dcf-00a1-4e34-98d4-5c47484a36d4</tns:ParentGUID>
		</tns:Addrobj>
		<tns:Addrobj>
			<tns:AOLevel>1</tns:AOLevel>
			<tns:FormalName>Московская область</tns:FormalName>
			<tns:ShortName>обл</tns:ShortName>
			<tns:AOGUID>29251dcf-00a1-4e34-98d4-5c47484a36d4</tns:AOGUID>
		</tns:Addrobj>
	</tns:AggregatedRequest>
</tns:exportAddressAdditionResponse>
